### PR TITLE
Pipelines ux iii

### PR DESCRIPTION
**Pull request by snopoke**
## Description
There are a lot of changes. I'll highlight the main ones (also see the demo):
* Input and output handles are placed at the top left and bottom right of the nodes
* Handles have a label which appears next to the handle (inside the node)
* The nodes only show selected parameters with a side panel available to edit all the params
* Some widgets have been re-worked:
  * LLM Provider and LLM Model have been combined into a single dropdown
  * History type & name have been combined
  * Number of outputs and output keywords have been combined and the UI has been updated to manage the 'number of outputs' directly

## User Impact
A nicer UI.

### Demo
<div>
    <a href="https://www.loom.com/share/f79f7d5d06924c318f4f09b5b77f9b04">
      <p>Dimagi Chatbots | Pipeline updates III - 29 October 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/f79f7d5d06924c318f4f09b5b77f9b04">
      
    </a>
  </div>

### CODE REVIEW

**Comment by snopoke** [comment]
@coderabbit review

**Comment by snopoke** [comment]
@coderabbit review

**Comment by snopoke** [comment]
@coderabbit resolve

**Review by SmittieC — APPROVED** [review]
Looks great! No considerable comments from my side for now

**Pull request merged**
