### PR TITLE
Voice providers part 2

### PR DESCRIPTION
**Pull request by snopoke**
PR on top of https://github.com/dimagi/open-chat-studio/pull/88

This is the final piece for per-team voice providers (no more global Azure / AWS voice keys).

This links team voice providers to experiments and updates the UI to support selecting them and filtering the list of synthetic voices (see demo below).

It also refactors the audio generation code to make it easier to call.

### UI demo
Peek 2023-10-26 15-56

### Notes

Can only be deployed after https://github.com/dimagi/open-chat-studio/pull/88 has been deployed.

Resolves https://github.com/dimagi/open-chat-studio/issues/82

### CODE REVIEW

**Comment by snopoke** [comment]
This can now be deployed.

**Comment by bderenzi** [comment]
I'm just going off the GIF above, but as per #68 / #80 (sorry for the duplicate), can we sort the voices? I think we can also change the string to remove the service now that they are pre-filtered. That will make it easier for users to find the correct voice.

**Comment by snopoke** [comment]
@SmittieC please can you review this - most of the other's are based off this branch so I'd prefer to merge this first.

**Review by SmittieC — COMMENTED** [review]
Where are the voice providers created?

**Comment by SmittieC** [comment]
> @SmittieC please can you review this - most of the other's are based off this branch so I'd prefer to merge this first.

Sorry got caught up on other stuff. Just finished looking through this. Looks good from my side, so approving, but I do have 1 non-blocking question

**Review by SmittieC — APPROVED** [review]

**Comment by snopoke** [comment]
> Where are the voice providers created?

From the team page - basically the same as the LLM Providers

**Pull request merged**
